"""Sovereign mission logic for the Meta-Agentic α-AGI Jobs Demo V9."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent
from typing import Any, Dict, Iterable, List, Mapping, Sequence

from meta_agentic_alpha_demo import DemoConfiguration, DemoOutcome, load_configuration, run_demo
from meta_agentic_alpha_v8 import (
    OwnerConvergenceMandate as BaseMandate,
    generate_convergence_dashboard as generate_v8_dashboard,
    validate_owner_mandate as validate_v8_mandate,
)

DEMO_ROOT = Path(__file__).resolve().parents[2]
PACKAGE_ROOT = DEMO_ROOT / "meta_agentic_alpha_v9"
DEFAULT_CONFIG_PATH = PACKAGE_ROOT / "config" / "scenario.yaml"


@dataclass(frozen=True)
class OwnerSovereigntyMandate:
    """Validated owner empowerment profile for the V9 demo."""

    base: BaseMandate
    mission_threads: List[str]
    sovereign_domains: List[str]
    unstoppable_initiatives: List[str]
    telemetry_channels: List[str]
    autopilot_modes: Mapping[str, Any]
    upgrade_scripts: Mapping[str, str]
    ci_checks: Sequence[str]
    treasury_streams: Sequence[Mapping[str, Any]]
    owner_prompts: Sequence[str]
    unstoppable_switches: Mapping[str, Any]
    unstoppable_threshold: float

    @property
    def guardians(self) -> List[str]:
        return self.base.guardians

    @property
    def guardian_failover(self) -> List[str]:
        return self.base.guardian_failover

    @property
    def approvals_required(self) -> int:
        return self.base.approvals_required

    @property
    def emergency_pause(self) -> bool:
        return self.base.emergency_pause

    @property
    def antifragility_buffer_percent(self) -> float:
        return self.base.antifragility_buffer_percent

    @property
    def unstoppable_reserve_percent(self) -> float:
        return self.base.unstoppable_reserve_percent

    @property
    def delegation_matrix(self) -> Mapping[str, Any]:
        return self.base.delegation_matrix

    @property
    def circuit_breaker_window_minutes(self) -> int:
        return self.base.circuit_breaker_window_minutes

    @property
    def session_keys(self) -> List[str]:
        return self.base.session_keys

    @property
    def bundler(self) -> str:
        return self.base.bundler

    @property
    def paymaster(self) -> str:
        return self.base.paymaster

    @property
    def treasury_policy(self) -> Mapping[str, Any]:
        return self.base.treasury_policy

    @property
    def control_scripts(self) -> Mapping[str, str]:
        return self.base.control_scripts

    @property
    def mutable_parameters(self) -> Mapping[str, Any]:
        return self.base.mutable_parameters

    @property
    def timelock_address(self) -> str:
        return self.base.timelock_address

    @property
    def multisig_address(self) -> str:
        return self.base.multisig_address

    @property
    def guardian_count(self) -> int:
        return self.base.guardian_count


@dataclass(frozen=True)
class MetaSovereigntyOutcome:
    """Composite artefacts generated by the V9 demo."""

    base: DemoOutcome
    summary_path: Path
    dashboard_path: Path
    report_path: Path
    scoreboard_path: Path
    dashboard_payload: Dict[str, Any]
    command_matrix: OwnerSovereigntyMandate


def _require_iterable(values: Iterable[Any], name: str, minimum: int) -> List[str]:
    sequence = [str(item).strip() for item in values if str(item).strip()]
    if len(sequence) < minimum:
        raise ValueError(f"{name} must provide at least {minimum} entries")
    return sequence


def _require_mapping(mapping: Mapping[str, Any], name: str, minimum: int) -> Mapping[str, Any]:
    if not isinstance(mapping, Mapping) or len(mapping) < minimum:
        raise ValueError(f"{name} must define at least {minimum} entries")
    return mapping


def validate_owner_sovereignty(config: DemoConfiguration) -> OwnerSovereigntyMandate:
    """Validate the V9 scenario delivers unstoppable sovereign control."""

    base_mandate = validate_v8_mandate(config)
    scenario = config.payload.get("scenario", {})
    owner = scenario.get("owner", {})
    treasury = scenario.get("treasury", {})
    operations = scenario.get("operations", {})
    ci = scenario.get("ci", {})

    mission_threads = _require_iterable(owner.get("mission_threads", []), "owner.mission_threads", 3)
    sovereign_domains = _require_iterable(owner.get("sovereign_domains", []), "owner.sovereign_domains", 4)
    unstoppable_initiatives = _require_iterable(
        scenario.get("unstoppable_initiatives", []), "scenario.unstoppable_initiatives", 4
    )
    telemetry_channels = _require_iterable(
        operations.get("telemetry_channels", []), "operations.telemetry_channels", 3
    )
    autopilot_modes = _require_mapping(operations.get("autopilot_modes", {}), "operations.autopilot_modes", 3)
    upgrade_scripts = _require_mapping(owner.get("upgrade_scripts", {}), "owner.upgrade_scripts", 3)
    ci_checks = _require_iterable(ci.get("checks", []), "ci.checks", 6)
    treasury_streams = treasury.get("streams", [])
    if not isinstance(treasury_streams, Sequence) or len(treasury_streams) < 4:
        raise ValueError("treasury.streams must declare at least four capital routes")
    owner_prompts = _require_iterable(operations.get("owner_prompts", []), "operations.owner_prompts", 3)
    unstoppable_switches = _require_mapping(owner.get("unstoppable_switches", {}), "owner.unstoppable_switches", 3)
    unstoppable_threshold = float(owner.get("unstoppable_threshold", 0.0))
    if unstoppable_threshold < 0.9:
        raise ValueError("owner.unstoppable_threshold must be at least 0.9")

    return OwnerSovereigntyMandate(
        base=base_mandate,
        mission_threads=mission_threads,
        sovereign_domains=sovereign_domains,
        unstoppable_initiatives=unstoppable_initiatives,
        telemetry_channels=telemetry_channels,
        autopilot_modes=dict(autopilot_modes),
        upgrade_scripts={str(key): str(value) for key, value in upgrade_scripts.items()},
        ci_checks=ci_checks,
        treasury_streams=list(treasury_streams),
        owner_prompts=owner_prompts,
        unstoppable_switches=dict(unstoppable_switches),
        unstoppable_threshold=unstoppable_threshold,
    )


def prepare_environment(demo_root: Path) -> Dict[str, Path]:
    """Prepare isolated storage directories and env vars for V9 runs."""

    orchestrator_root = demo_root / "storage" / "orchestrator_v9"
    orchestrator_root.mkdir(parents=True, exist_ok=True)
    (orchestrator_root / "agents").mkdir(parents=True, exist_ok=True)
    (orchestrator_root / "runs").mkdir(parents=True, exist_ok=True)

    env_map = {
        "ORCHESTRATOR_BRIDGE_MODE": "python",
        "ORCHESTRATOR_SCOREBOARD_PATH": orchestrator_root / "scoreboard.json",
        "ORCHESTRATOR_CHECKPOINT_PATH": orchestrator_root / "checkpoint.json",
        "ORCHESTRATOR_CHECKPOINT_LEVELDB": orchestrator_root / "checkpoint.db",
        "ORCHESTRATOR_GOVERNANCE_PATH": orchestrator_root / "governance.json",
        "ORCHESTRATOR_STATE_DIR": orchestrator_root / "runs",
        "AGENT_REGISTRY_PATH": orchestrator_root / "agents" / "registry.json",
    }
    for key, value in env_map.items():
        os.environ[key] = str(value)
    return env_map


def _load_json(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected mapping payload at {path}")
    return payload


def generate_sovereignty_dashboard(
    package_root: Path,
    summary: Dict[str, Any],
    scoreboard: Dict[str, Any],
    command: OwnerSovereigntyMandate,
) -> Dict[str, Any]:
    """Generate the V9 Sovereign Meta-Agentic console payload."""

    base_payload = generate_v8_dashboard(package_root, summary, scoreboard, command.base)

    data_root = package_root / "data"
    sovereignty = _load_json(data_root / "sovereignty_matrix.json")
    mission_threads = _load_json(data_root / "mission_threads.json")
    autopilot = _load_json(data_root / "autopilot_protocols.json")
    treasury_streams = _load_json(data_root / "treasury_streams.json")
    unstoppable_matrix = _load_json(data_root / "unstoppable_matrix.json")
    ci_v2 = _load_json(data_root / "ci_v2.json")

    metrics = base_payload.setdefault("metrics", {})
    owner_empowerment = min(
        1.0,
        metrics.get("owner_empowerment", 0.0)
        + 0.07
        + 0.01 * len(command.sovereign_domains)
        + 0.01 * len(command.mission_threads),
    )
    unstoppable_readiness = min(
        1.0,
        metrics.get("unstoppable_readiness", 0.0)
        + 0.12
        + 0.02 * len(command.unstoppable_initiatives)
        + 0.01 * len(command.unstoppable_switches),
    )
    sovereignty_index = min(
        1.0,
        0.58
        + 0.05 * len(command.telemetry_channels)
        + 0.05 * len(command.autopilot_modes)
        + 0.04 * len(command.treasury_streams)
        + 0.03 * len(command.owner_prompts)
        + 0.04 * len(command.mission_threads),
    )
    autopilot_mastery = min(
        1.0,
        0.55
        + 0.04 * len(autopilot.get("modes", []))
        + 0.03 * len(command.autopilot_modes)
        + 0.04 * len(command.session_keys),
    )
    meta_ci_health = min(
        1.0,
        0.62 + 0.04 * len(command.ci_checks) + (0.06 if ci_v2.get("status") == "green" else 0.03),
    )
    alpha_forge_velocity = min(
        1.0,
        0.57
        + 0.05 * len(mission_threads.get("threads", []))
        + 0.04 * len(command.mission_threads)
        + 0.05 * len(command.autopilot_modes),
    )
    guardian_resilience = min(
        1.0,
        metrics.get("guardian_resilience", 0.0)
        + 0.05 * len(command.sovereign_domains)
        + 0.03 * len(command.guardian_failover),
    )
    capital_flywheel_index = min(
        1.0,
        metrics.get("capital_flywheel_index", 0.0)
        + 0.06 * len(command.treasury_streams)
        + 0.05 * sovereignty_index,
    )

    metrics.update(
        {
            "owner_empowerment": owner_empowerment,
            "unstoppable_readiness": unstoppable_readiness,
            "sovereignty_index": sovereignty_index,
            "autopilot_mastery": autopilot_mastery,
            "meta_ci_health": meta_ci_health,
            "alpha_forge_velocity": alpha_forge_velocity,
            "guardian_resilience": guardian_resilience,
            "capital_flywheel_index": capital_flywheel_index,
            "owner_command_latency_seconds": unstoppable_matrix.get("command_latency_seconds", 9),
            "owner_approval_speed_minutes": unstoppable_matrix.get("owner_approval_speed_minutes", 2),
            "scoreboard": scoreboard,
        }
    )

    control_surface = base_payload.setdefault("control_surface", {})
    control_surface.update(
        {
            "sovereign_domains": command.sovereign_domains,
            "mission_threads": command.mission_threads,
            "unstoppable_initiatives": command.unstoppable_initiatives,
            "telemetry_channels": command.telemetry_channels,
            "autopilot_modes": command.autopilot_modes,
            "upgrade_scripts": command.upgrade_scripts,
            "owner_prompts": command.owner_prompts,
            "unstoppable_switches": command.unstoppable_switches,
            "unstoppable_threshold": command.unstoppable_threshold,
        }
    )

    mermaid = base_payload.setdefault("mermaid", {})
    mermaid_flow = dedent(
        """
        graph TD
          Owner((Sovereign Owner)) --> Identify[Identify Mesh]
          Identify --> Learn[Open-Ended Curriculum]
          Learn --> Think[Meta-Agentic Planner]
          Think --> Design[Creative HyperForge]
          Design --> Strategise[Portfolio Navigator]
          Strategise --> Execute[On-Chain Execution Fabric]
          Execute --> Govern[Guardian Meta-Mesh]
          Govern --> Sustain[Owner Sovereignty Atlas]
          Sustain --> Owner
          Owner -->|Override Scripts| Execute
          Owner -->|Parameter Switches| Strategise
          subgraph Sovereignty["Sovereignty Flywheel"]
            Telemetry((Telemetry))
            Autopilot((Autopilot))
            Treasury((Treasury))
            Guardians((Guardian Mesh))
            CI((CI V2 Grid))
            Telemetry --> Autopilot
            Autopilot --> Treasury
            Treasury --> Guardians
            Guardians --> CI
            CI --> Execute
          end
          Execute --> Sovereignty
          Sovereignty --> Execute
        """
    ).strip()

    mermaid_radar = dedent(
        f"""
        %%{{init: {{'theme': 'dark'}} }}%%
        radarChart
          title Sovereign Capability Radar
          axes Automation, Resilience, Empowerment, Velocity, Stewardship
          dataset Owner
            data {owner_empowerment:.2f}, {guardian_resilience:.2f}, {sovereignty_index:.2f}, {alpha_forge_velocity:.2f}, {meta_ci_health:.2f}
        """
    ).strip()

    mermaid_sequence = dedent(
        """
        sequenceDiagram
          participant Owner as Sovereign Owner
          participant Console as Sovereignty Console
          participant Planner as Meta-Agentic Planner
          participant Guardians as Guardian Council
          participant Chain as AGI Jobs v0 (v2)
          Owner->>Console: Launch Sovereignty Mission
          Console->>Planner: Upload V9 scenario YAML
          Planner->>Guardians: Stream unstoppable levers & antifragility checks
          Guardians->>Chain: Simulate 4337 execution + treasury routing
          Chain-->>Console: CI V2 verdicts + receipts + telemetry
          Console-->>Owner: Render sovereign dashboard & override levers
          Owner->>Chain: Optional unstoppable switch execution
        """
    ).strip()

    mermaid_timeline = dedent(
        """
        gantt
          title Meta-Agentic Sovereignty Timeline
          dateFormat X
          axisFormat %s
          section Identify
            Hyper-signal fusion       :done,    0, 1
            Antifragility anomaly scan:active,  1, 1
          section Learn
            Curriculum escalation     :        2, 1
            World model distillation  :        3, 2
          section Strategise
            Treasury sovereignty mesh :        5, 1
            Guardian quorum sync      :        6, 1
          section Execute
            4337 dry-run envelope     :        7, 1
            On-chain execution        :        8, 1
            Owner override window     :        9, 1
        """
    ).strip()

    mermaid_mindmap = dedent(
        """
        mindmap
          root((Sovereign Meta-Agent))
            Identify
              Multi-domain feeds
              Alpha anomaly triage
            Learn
              Curriculum auto-escalation
              MuZero world modelling
            Think
              Meta-agentic search lattice
              Guardian quorum modelling
            Design
              HyperForge creative labs
              Simulation sweeps
            Strategise
              Treasury sovereignty mesh
              Portfolio flywheel
            Execute
              4337 execution fabric
              Gasless owner overrides
            Govern
              CI V2 enforcement
              Owner sovereignty atlas
        """
    ).strip()

    mermaid_journey = dedent(
        """
        journey
          title Owner Empowerment Journey V9
          section Console
            Launch sovereignty CLI: 5: owner
            Review unstoppable dashboard: 5: owner
            Trigger override switch: 4: owner
          section Guardians
            Confirm quorum: 5: guardians
            Approve antifragility probes: 4: guardians
            Endorse unstoppable threshold: 5: guardians
        """
    ).strip()

    mermaid_state = dedent(
        """
        stateDiagram-v2
          [*] --> SovereignReady
          SovereignReady --> Identify
          Identify --> Learn
          Learn --> Think
          Think --> Design
          Design --> Strategise
          Strategise --> Execute
          Execute --> SovereignReview
          SovereignReview --> Execute: Override Script
          SovereignReview --> [*]
        """
    ).strip()

    mermaid_quadrant = dedent(
        """
        quadrantChart
          title Sovereign Command Quadrant
          x-axis Automation <---> Human Oversight
          y-axis Passive <---> Proactive
          "Owner Override Mesh" : 0.40 : 0.88
          "Guardian Meta-Mesh" : -0.10 : 0.92
          "CI Enforcement" : 0.62 : 0.66
          "Alpha Factories" : 0.82 : 0.42
          "Autopilot Orchestrators" : 0.55 : 0.78
        """
    ).strip()

    mermaid.update(
        {
            "flow_v9": mermaid_flow,
            "radar": mermaid_radar,
            "sequence_v9": mermaid_sequence,
            "gantt_v9": mermaid_timeline,
            "mindmap_v9": mermaid_mindmap,
            "journey_v9": mermaid_journey,
            "state_v9": mermaid_state,
            "quadrant_v9": mermaid_quadrant,
        }
    )

    base_payload.update(
        {
            "sovereignty": sovereignty,
            "mission_threads": mission_threads,
            "autopilot": autopilot,
            "treasury_streams": treasury_streams,
            "unstoppable_matrix": unstoppable_matrix,
            "ci_v2": ci_v2,
            "command_matrix": {
                "mission_threads": command.mission_threads,
                "unstoppable_initiatives": command.unstoppable_initiatives,
                "telemetry_channels": command.telemetry_channels,
                "autopilot_modes": command.autopilot_modes,
            },
        }
    )
    base_payload.setdefault("metrics", {})
    base_payload["metrics"]["scoreboard"] = scoreboard
    return base_payload


def generate_sovereignty_report(package_root: Path, summary: Dict[str, Any], dashboard: Dict[str, Any]) -> Path:
    """Render the V9 Sovereign Masterplan markdown deck."""

    reports_dir = package_root / "reports" / "generated"
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / "alpha_meta_sovereignty_masterplan.md"

    timeline_block = dashboard.get("timeline", {})
    if isinstance(timeline_block, Mapping):
        timeline_events = timeline_block.get("events", [])
    else:
        timeline_events = timeline_block
    sovereignty = dashboard.get("sovereignty", {})
    mission_threads = dashboard.get("mission_threads", {}).get("threads", [])

    report = dedent(
        f"""
        # Meta-Agentic α-AGI Jobs Demo V9 — Sovereignty Masterplan

        ## Mission Summary

        - Scenario: {summary.get('scenarioId')}
        - Run ID: {summary.get('runId', 'N/A')}
        - Guardian approvals: {', '.join(summary.get('approvals', [])) or 'N/A'}
        - Agents onboarded: {', '.join(summary.get('agents', [])) or 'N/A'}

        ## Sovereign Metrics

        - Owner empowerment: {dashboard['metrics']['owner_empowerment']*100:.2f}%
        - Sovereignty index: {dashboard['metrics']['sovereignty_index']*100:.2f}%
        - Unstoppable readiness: {dashboard['metrics']['unstoppable_readiness']*100:.2f}%
        - Autopilot mastery: {dashboard['metrics']['autopilot_mastery']*100:.2f}%
        - Meta-CI health: {dashboard['metrics']['meta_ci_health']*100:.2f}%
        - Alpha forge velocity: {dashboard['metrics']['alpha_forge_velocity']*100:.2f}%
        - Guardian resilience: {dashboard['metrics']['guardian_resilience']*100:.2f}%
        - Capital flywheel index: {dashboard['metrics']['capital_flywheel_index']*100:.2f}%
        - Owner command latency: {dashboard['metrics']['owner_command_latency_seconds']} seconds
        - Owner approval speed: {dashboard['metrics']['owner_approval_speed_minutes']} minutes

        ## Sovereign Capability Radar

        ```mermaid
        {dashboard['mermaid']['radar']}
        ```

        ## Sovereignty Flywheel Flow

        ```mermaid
        {dashboard['mermaid']['flow_v9']}
        ```

        ## Guardian Coordination Sequence

        ```mermaid
        {dashboard['mermaid']['sequence_v9']}
        ```

        ## Timeline

        ```mermaid
        {dashboard['mermaid']['gantt_v9']}
        ```

        ## Owner Journey

        ```mermaid
        {dashboard['mermaid']['journey_v9']}
        ```

        ## Sovereign State Machine

        ```mermaid
        {dashboard['mermaid']['state_v9']}
        ```

        ## Command Quadrant

        ```mermaid
        {dashboard['mermaid']['quadrant_v9']}
        ```

        ## Sovereignty Matrix

        ```json
        {json.dumps(sovereignty, indent=2)}
        ```

        ## Mission Threads

        {os.linesep.join(f"- **{item['id']}** — {item['title']}" for item in mission_threads)}

        ## Execution Timeline

        {os.linesep.join(f"- **{event['time']}** — {event['event']}" for event in timeline_events)}

        ## Scoreboard Snapshot

        ```json
        {json.dumps(dashboard['metrics']['scoreboard'], indent=2)}
        ```
        """
    ).strip() + "\n"

    path.write_text(report, encoding="utf-8")
    return path


def run_meta_sovereignty_demo(
    config_path: Path | None = None,
    *,
    timeout: float = 210.0,
) -> MetaSovereigntyOutcome:
    """Execute the Meta-Agentic α-AGI Jobs V9 demo end-to-end."""

    if config_path is None:
        config_path = DEFAULT_CONFIG_PATH
    config = load_configuration(config_path)
    command_matrix = validate_owner_sovereignty(config)

    package_root = config.base_dir
    demo_root = package_root.parent

    env_map = prepare_environment(demo_root)
    outcome = run_demo(config, timeout=timeout)

    summary = json.loads(outcome.summary_path.read_text(encoding="utf-8"))
    summary["approvals"] = config.approvals
    summary["scenarioId"] = config.payload.get("scenario", {}).get("id")
    summary["agents"] = outcome.metadata.get("onboarded_agents", [])

    scoreboard_path = Path(env_map["ORCHESTRATOR_SCOREBOARD_PATH"])
    scoreboard = outcome.scoreboard_snapshot or {}
    if not scoreboard_path.exists():
        scoreboard_path.write_text(json.dumps(scoreboard, ensure_ascii=False, indent=2), encoding="utf-8")

    dashboard_payload = generate_sovereignty_dashboard(package_root, summary, scoreboard, command_matrix)
    dashboard_path = package_root / "ui" / "dashboard-data-v9.json"
    dashboard_path.write_text(json.dumps(dashboard_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    report_path = generate_sovereignty_report(package_root, summary, dashboard_payload)

    latest_run_path = demo_root / "storage" / "latest_run_v9.json"
    latest_run_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    return MetaSovereigntyOutcome(
        base=outcome,
        summary_path=latest_run_path,
        dashboard_path=dashboard_path,
        report_path=report_path,
        scoreboard_path=scoreboard_path,
        dashboard_payload=dashboard_payload,
        command_matrix=command_matrix,
    )


__all__ = [
    "DEFAULT_CONFIG_PATH",
    "OwnerSovereigntyMandate",
    "MetaSovereigntyOutcome",
    "prepare_environment",
    "validate_owner_sovereignty",
    "generate_sovereignty_dashboard",
    "generate_sovereignty_report",
    "run_meta_sovereignty_demo",
]
