image:
  repository: ghcr.io/agi/jobs/attester
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 7000
resources: {}
config:
  rpcUrl: https://ethereum-sepolia.publicnode.com
  easSchemaUid: "0x0000000000000000000000000000000000000000000000000000000000000000"
  kmsKey: projects/example/locations/global/keyRings/agi/cryptoKeys/attester
  corsOrigins:
    - https://operator.example.com
monitoring:
  enabled: true
