global: {}
replicaCount: 1
image:
  repository: attester
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8060
resources: {}
podAnnotations: {}
autoscaling:
  enabled: false
eas: {}
extraEnvFrom: []
