replicaCount: 1
image:
  repository: ipfs/kubo
  tag: v0.22.0
  digest: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5001
  swarmPort: 4001
  gatewayPort: 8080
persistence:
  enabled: true
  size: 50Gi
  storageClass: ""
resources: {}
