global: {}
replicaCount: 1
image:
  repository: orchestrator
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
podAnnotations: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: null
env: {}
eas: {}
extraEnvFrom: []
serviceAccountRoleArn: null
