{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orchestrator.fullname" . }}
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ join "," (.Values.env.corsOrigins | default (list "*")) | quote }}
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,POST,OPTIONS"
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.rateLimit.requestsPerMinute }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{ div .Values.env.maxRequestBytes 1024 }}k"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecret }}
      hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "orchestrator.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
