[profile.default]
solc_version = "0.8.25"
via_ir = true
optimizer = true
optimizer_runs = 200
src = "contracts"
test = "test"
libs = ["../../lib", "../../node_modules"]
remappings = [
  "@openzeppelin/contracts=../../node_modules/@openzeppelin/contracts"
]

[fmt]
line_length = 120
number_underscore = "thousands"
