from __future__ import annotations

import json
import statistics
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List

from .tasks import IterationSummary


@dataclass
class TelemetryRecord:
    iteration: int
    proposer_valid_rate: float
    solver_success_rate: float
    diversity_score: float
    gmv_total: float
    cost_total: float
    roi: float
    notes: List[str] = field(default_factory=list)


class TelemetryStream:
    def __init__(self, report_path: str, json_path: str, mermaid_theme: str = "forest") -> None:
        self.records: List[TelemetryRecord] = []
        self.report_path = Path(report_path)
        self.json_path = Path(json_path)
        self.mermaid_theme = mermaid_theme

    def append(self, record: TelemetryRecord) -> None:
        self.records.append(record)

    def summarise(self) -> Dict[str, Any]:
        if not self.records:
            return {}
        avg_success = statistics.mean(record.solver_success_rate for record in self.records)
        avg_valid = statistics.mean(record.proposer_valid_rate for record in self.records)
        final_roi = self.records[-1].roi
        return {
            "iterations": len(self.records),
            "avg_success_rate": round(avg_success, 3),
            "avg_valid_rate": round(avg_valid, 3),
            "final_roi": round(final_roi, 2),
        }

    def export(self) -> None:
        self.json_path.parent.mkdir(parents=True, exist_ok=True)
        self.report_path.parent.mkdir(parents=True, exist_ok=True)
        with self.json_path.open("w", encoding="utf-8") as fh:
            json.dump([record.__dict__ for record in self.records], fh, indent=2)
        with self.report_path.open("w", encoding="utf-8") as fh:
            fh.write(self._render_markdown())

    def _render_markdown(self) -> str:
        lines = [
            "# Absolute Zero Reasoner Economic Telemetry",
            "",
            "This report is automatically generated by the Absolute Zero Reasoner demo pipeline.",
            "",
            "```mermaid",
            f"%%{{init: {{'theme': '{self.mermaid_theme}'}} }}",
            "lineChart",
            "    title Solver Success Rate",
            "    xAxis Iteration",
            "    yAxis Success",
            "    series",
        ]
        for record in self.records:
            lines.append(f"        {record.iteration}:{record.solver_success_rate:.2f}")
        lines.extend([
            "```",
            "",
            "| Iteration | Success Rate | Valid Rate | Diversity | GMV (USD) | Cost (USD) | ROI (USD) | Notes |",
            "|-----------|--------------|------------|-----------|-----------|-----------|-----------|-------|",
        ])
        for record in self.records:
            notes = "; ".join(record.notes)
            lines.append(
                f"| {record.iteration} | {record.solver_success_rate:.2f} | {record.proposer_valid_rate:.2f} | {record.diversity_score:.2f} | "
                f"{record.gmv_total:.2f} | {record.cost_total:.2f} | {record.roi:.2f} | {notes} |"
            )
        lines.append("")
        return "\n".join(lines)


__all__ = ["TelemetryStream", "TelemetryRecord"]
