gantt
    title Global Expansion Cadence
    dateFormat  X
    Phase_I___Testnet_Supremacy :done, phase_0, 72h
    Phase_II___Mainnet_Pilot_Cohort :done, phase_1, 240h
    Phase_III___Planetary_Expansion_Mesh :done, phase_2, 720h
    Phase_IV___Governance_Acceleration :done, phase_3, 1440h
