[profile.default]
solc_version = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 500
src = "contracts"
test = "forge-test"
libs = ["../../lib", "../../node_modules"]
remappings = ['@openzeppelin/contracts=../../node_modules/@openzeppelin/contracts']

[fmt]
line_length = 120
