apiVersion: v1
kind: Service
metadata:
  name: {{ include "attester.fullname" . }}
  labels:
    app.kubernetes.io/name: attester
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: attester
    app.kubernetes.io/instance: {{ .Release.Name }}
