apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
    - name: swarm
      port: {{ .Values.service.swarmPort }}
      targetPort: swarm
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
