apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ipfs.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ipfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ipfs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ipfs
          image: {{ include "ipfs.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
            - name: swarm
              containerPort: {{ .Values.service.swarmPort }}
            - name: gateway
              containerPort: {{ .Values.service.gatewayPort }}
          volumeMounts:
            - name: data
              mountPath: /data/ipfs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
    {{- else }}
    []
    {{- end }}
