apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
stringData:
  postgres-user: {{ .Values.postgresUser | quote }}
  postgres-password: {{ .Values.postgresPassword | quote }}
  postgres-database: {{ .Values.postgresDatabase | quote }}
