apiVersion: v2
name: full-stack
version: 0.1.0
kubeVersion: ">=1.26.0"
description: Helm umbrella chart for the modular account abstraction stack
keywords:
  - aa
  - bundler
  - paymaster
  - orchestrator
  - ipfs
  - subgraph
home: https://github.com/organization/project
sources:
  - https://github.com/organization/project
maintainers:
  - name: SRE Team
    email: sre@example.com
dependencies:
  - name: orchestrator
    version: 0.1.0
    repository: "file://charts/orchestrator"
  - name: bundler
    version: 0.1.0
    repository: "file://charts/bundler"
  - name: paymaster-supervisor
    version: 0.1.0
    repository: "file://charts/paymaster-supervisor"
  - name: ipfs
    version: 0.1.0
    repository: "file://charts/ipfs"
  - name: graph-node
    version: 0.1.0
    repository: "file://charts/graph-node"
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
  - name: attester
    version: 0.1.0
    repository: "file://charts/attester"
  - name: ingress
    version: 0.1.0
    repository: "file://charts/ingress"
