apiVersion: v2
name: agi-stack
version: 0.1.0
description: Full AGI stack umbrella chart
appVersion: "0.1.0"
type: application
dependencies:
  - name: orchestrator
    version: 0.1.0
    repository: "file://../orchestrator"
  - name: bundler
    version: 0.1.0
    repository: "file://../bundler"
  - name: paymaster-supervisor
    version: 0.1.0
    repository: "file://../paymaster-supervisor"
  - name: ipfs
    version: 0.1.0
    repository: "file://../ipfs"
  - name: graph-node
    version: 0.1.0
    repository: "file://../graph-node"
  - name: postgres
    version: 0.1.0
    repository: "file://../postgres"
  - name: attester
    version: 0.1.0
    repository: "file://../attester"
  - name: ingress
    version: 0.1.0
    repository: "file://../ingress"
