image:
  repository: ipfs/go-ipfs
  tag: v0.23.0
  pullPolicy: IfNotPresent
service:
  apiPort: 5001
  swarmPort: 4001
  gatewayPort: 8080
persistence:
  enabled: true
  size: 50Gi
resources: {}
config:
  profile: server
  swarmKeySecret: ""
monitoring:
  enabled: true
