"""Supremacy mission logic for the Meta-Agentic α-AGI Jobs Demo V10."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent
from typing import Any, Dict, Iterable, List, Mapping, Sequence

from meta_agentic_alpha_demo import DemoConfiguration, DemoOutcome, load_configuration, run_demo
from meta_agentic_alpha_v8 import (
    OwnerConvergenceMandate as BaseMandate,
    generate_convergence_dashboard as generate_v8_dashboard,
    validate_owner_mandate as validate_v8_mandate,
)

DEMO_ROOT = Path(__file__).resolve().parents[2]
PACKAGE_ROOT = DEMO_ROOT / "meta_agentic_alpha_v10"
DEFAULT_CONFIG_PATH = PACKAGE_ROOT / "config" / "scenario.yaml"


@dataclass(frozen=True)
class OwnerSupremacyMandate:
    """Validated owner empowerment profile for the V10 demo."""

    base: BaseMandate
    mission_threads: List[str]
    sovereign_domains: List[str]
    unstoppable_initiatives: List[str]
    telemetry_channels: List[str]
    autopilot_modes: Mapping[str, Any]
    upgrade_scripts: Mapping[str, str]
    ci_checks: Sequence[str]
    treasury_streams: Sequence[Mapping[str, Any]]
    owner_prompts: Sequence[str]
    unstoppable_switches: Mapping[str, Any]
    unstoppable_threshold: float
    supremacy_vectors: Sequence[str]
    antifragility_programs: Sequence[str]
    cross_chain_bridges: Sequence[str]
    gasless_controls: Mapping[str, Any]

    @property
    def guardians(self) -> List[str]:
        return self.base.guardians

    @property
    def guardian_failover(self) -> List[str]:
        return self.base.guardian_failover

    @property
    def approvals_required(self) -> int:
        return self.base.approvals_required

    @property
    def emergency_pause(self) -> bool:
        return self.base.emergency_pause

    @property
    def antifragility_buffer_percent(self) -> float:
        return self.base.antifragility_buffer_percent

    @property
    def unstoppable_reserve_percent(self) -> float:
        return self.base.unstoppable_reserve_percent

    @property
    def delegation_matrix(self) -> Mapping[str, Any]:
        return self.base.delegation_matrix

    @property
    def circuit_breaker_window_minutes(self) -> int:
        return self.base.circuit_breaker_window_minutes

    @property
    def session_keys(self) -> List[str]:
        return self.base.session_keys

    @property
    def bundler(self) -> str:
        return self.base.bundler

    @property
    def paymaster(self) -> str:
        return self.base.paymaster

    @property
    def treasury_policy(self) -> Mapping[str, Any]:
        return self.base.treasury_policy

    @property
    def control_scripts(self) -> Mapping[str, str]:
        return self.base.control_scripts

    @property
    def mutable_parameters(self) -> Mapping[str, Any]:
        return self.base.mutable_parameters

    @property
    def timelock_address(self) -> str:
        return self.base.timelock_address

    @property
    def multisig_address(self) -> str:
        return self.base.multisig_address

    @property
    def guardian_count(self) -> int:
        return self.base.guardian_count


@dataclass(frozen=True)
class MetaSupremacyOutcome:
    """Composite artefacts generated by the V10 demo."""

    base: DemoOutcome
    summary_path: Path
    dashboard_path: Path
    report_path: Path
    scoreboard_path: Path
    dashboard_payload: Dict[str, Any]
    command_matrix: OwnerSupremacyMandate


def _require_iterable(values: Iterable[Any], name: str, minimum: int) -> List[str]:
    sequence = [str(item).strip() for item in values if str(item).strip()]
    if len(sequence) < minimum:
        raise ValueError(f"{name} must provide at least {minimum} entries")
    return sequence


def _require_mapping(mapping: Mapping[str, Any], name: str, minimum: int) -> Mapping[str, Any]:
    if not isinstance(mapping, Mapping) or len(mapping) < minimum:
        raise ValueError(f"{name} must define at least {minimum} entries")
    return mapping


def validate_owner_supremacy(config: DemoConfiguration) -> OwnerSupremacyMandate:
    """Validate the V10 scenario delivers unstoppable sovereign control."""

    base_mandate = validate_v8_mandate(config)
    scenario = config.payload.get("scenario", {})
    owner = scenario.get("owner", {})
    treasury = scenario.get("treasury", {})
    operations = scenario.get("operations", {})
    ci = scenario.get("ci", {})

    mission_threads = _require_iterable(owner.get("mission_threads", []), "owner.mission_threads", 4)
    sovereign_domains = _require_iterable(owner.get("sovereign_domains", []), "owner.sovereign_domains", 5)
    unstoppable_initiatives = _require_iterable(
        scenario.get("unstoppable_initiatives", []), "scenario.unstoppable_initiatives", 5
    )
    telemetry_channels = _require_iterable(
        operations.get("telemetry_channels", []), "operations.telemetry_channels", 4
    )
    autopilot_modes = _require_mapping(operations.get("autopilot_modes", {}), "operations.autopilot_modes", 4)
    upgrade_scripts = _require_mapping(owner.get("upgrade_scripts", {}), "owner.upgrade_scripts", 4)
    ci_checks = _require_iterable(ci.get("checks", []), "ci.checks", 8)
    treasury_streams = treasury.get("streams", [])
    if not isinstance(treasury_streams, Sequence) or len(treasury_streams) < 5:
        raise ValueError("treasury.streams must declare at least five capital routes")
    owner_prompts = _require_iterable(operations.get("owner_prompts", []), "operations.owner_prompts", 4)
    unstoppable_switches = _require_mapping(owner.get("unstoppable_switches", {}), "owner.unstoppable_switches", 4)
    supremacy_vectors = _require_iterable(owner.get("supremacy_vectors", []), "owner.supremacy_vectors", 4)
    antifragility_programs = _require_iterable(
        operations.get("antifragility_programs", []), "operations.antifragility_programs", 3
    )
    cross_chain_bridges = _require_iterable(treasury.get("bridge_channels", []), "treasury.bridge_channels", 3)
    gasless_controls = _require_mapping(operations.get("gasless_controls", {}), "operations.gasless_controls", 2)
    unstoppable_threshold = float(owner.get("unstoppable_threshold", 0.0))
    if unstoppable_threshold < 0.93:
        raise ValueError("owner.unstoppable_threshold must be at least 0.93")

    return OwnerSupremacyMandate(
        base=base_mandate,
        mission_threads=mission_threads,
        sovereign_domains=sovereign_domains,
        unstoppable_initiatives=unstoppable_initiatives,
        telemetry_channels=telemetry_channels,
        autopilot_modes=dict(autopilot_modes),
        upgrade_scripts={str(key): str(value) for key, value in upgrade_scripts.items()},
        ci_checks=ci_checks,
        treasury_streams=list(treasury_streams),
        owner_prompts=owner_prompts,
        unstoppable_switches=dict(unstoppable_switches),
        unstoppable_threshold=unstoppable_threshold,
        supremacy_vectors=supremacy_vectors,
        antifragility_programs=antifragility_programs,
        cross_chain_bridges=cross_chain_bridges,
        gasless_controls=dict(gasless_controls),
    )


def prepare_environment(demo_root: Path) -> Dict[str, Path]:
    """Prepare isolated storage directories and env vars for V10 runs."""

    orchestrator_root = demo_root / "storage" / "orchestrator_v10"
    orchestrator_root.mkdir(parents=True, exist_ok=True)
    (orchestrator_root / "agents").mkdir(parents=True, exist_ok=True)
    (orchestrator_root / "runs").mkdir(parents=True, exist_ok=True)

    env_map: Dict[str, Any] = {
        "ORCHESTRATOR_BRIDGE_MODE": "python",
        "ORCHESTRATOR_SCOREBOARD_PATH": orchestrator_root / "scoreboard.json",
        "ORCHESTRATOR_CHECKPOINT_PATH": orchestrator_root / "checkpoint.json",
        "ORCHESTRATOR_CHECKPOINT_LEVELDB": orchestrator_root / "checkpoint.db",
        "ORCHESTRATOR_GOVERNANCE_PATH": orchestrator_root / "governance.json",
        "ORCHESTRATOR_STATE_DIR": orchestrator_root / "runs",
        "AGENT_REGISTRY_PATH": orchestrator_root / "agents" / "registry.json",
    }
    for key, value in env_map.items():
        os.environ[key] = str(value)
    return env_map


def _load_json(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected mapping payload at {path}")
    return payload


def generate_supremacy_dashboard(
    package_root: Path,
    summary: Dict[str, Any],
    scoreboard: Dict[str, Any],
    command: OwnerSupremacyMandate,
) -> Dict[str, Any]:
    """Generate the V10 Supremacy Meta-Agentic console payload."""

    base_payload = generate_v8_dashboard(package_root, summary, scoreboard, command.base)

    data_root = package_root / "data"
    supremacy = _load_json(data_root / "supremacy_matrix.json")
    mission_threads = _load_json(data_root / "mission_threads.json")
    autopilot = _load_json(data_root / "autopilot_protocols.json")
    treasury_streams = _load_json(data_root / "treasury_streams.json")
    unstoppable_matrix = _load_json(data_root / "unstoppable_matrix.json")
    ci_v2 = _load_json(data_root / "ci_v2.json")
    guardian_mesh = _load_json(data_root / "guardian_mesh.json")
    opportunity_graph = _load_json(data_root / "opportunity_graph.json")

    metrics = base_payload.setdefault("metrics", {})
    owner_empowerment = min(
        1.0,
        metrics.get("owner_empowerment", 0.0)
        + 0.1
        + 0.01 * len(command.sovereign_domains)
        + 0.02 * len(command.supremacy_vectors)
        + 0.01 * len(command.gasless_controls),
    )
    unstoppable_readiness = min(
        1.0,
        metrics.get("unstoppable_readiness", 0.0)
        + 0.14
        + 0.02 * len(command.unstoppable_initiatives)
        + 0.02 * len(command.unstoppable_switches)
        + 0.01 * len(command.cross_chain_bridges),
    )
    supremacy_index = min(
        1.0,
        0.62
        + 0.05 * len(command.telemetry_channels)
        + 0.05 * len(command.autopilot_modes)
        + 0.04 * len(command.treasury_streams)
        + 0.04 * len(command.mission_threads)
        + 0.03 * len(command.antifragility_programs),
    )
    autopilot_mastery = min(
        1.0,
        0.58
        + 0.04 * len(autopilot.get("modes", []))
        + 0.03 * len(command.autopilot_modes)
        + 0.03 * len(command.session_keys)
        + 0.02 * len(command.supremacy_vectors),
    )
    meta_ci_health = min(
        1.0,
        0.66 + 0.03 * len(command.ci_checks) + (0.08 if ci_v2.get("status") == "green" else 0.04),
    )
    guardian_resilience = min(
        1.0,
        metrics.get("guardian_resilience", 0.0)
        + 0.05 * len(command.guardians)
        + 0.04 * len(command.guardian_failover)
        + 0.03 * len(command.antifragility_programs),
    )
    capital_flywheel_index = min(
        1.0,
        metrics.get("capital_flywheel_index", 0.0)
        + 0.05 * len(command.treasury_streams)
        + 0.06 * supremacy_index
        + 0.02 * len(command.cross_chain_bridges),
    )
    expansion_thrust = min(
        1.0,
        0.59
        + 0.04 * len(opportunity_graph.get("insights", []))
        + 0.03 * len(command.supremacy_vectors)
        + 0.03 * len(command.unstoppable_initiatives),
    )

    metrics.update(
        {
            "owner_empowerment": owner_empowerment,
            "unstoppable_readiness": unstoppable_readiness,
            "supremacy_index": supremacy_index,
            "autopilot_mastery": autopilot_mastery,
            "meta_ci_health": meta_ci_health,
            "guardian_resilience": guardian_resilience,
            "capital_flywheel_index": capital_flywheel_index,
            "expansion_thrust": expansion_thrust,
            "owner_command_latency_seconds": supremacy.get("command_latency_seconds", 7),
            "owner_approval_speed_minutes": supremacy.get("owner_approval_speed_minutes", 1),
            "scoreboard": scoreboard,
        }
    )

    control_surface = base_payload.setdefault("control_surface", {})
    control_surface.update(
        {
            "sovereign_domains": command.sovereign_domains,
            "mission_threads": command.mission_threads,
            "supremacy_vectors": command.supremacy_vectors,
            "unstoppable_initiatives": command.unstoppable_initiatives,
            "telemetry_channels": command.telemetry_channels,
            "autopilot_modes": command.autopilot_modes,
            "upgrade_scripts": command.upgrade_scripts,
            "owner_prompts": command.owner_prompts,
            "antifragility_programs": command.antifragility_programs,
            "unstoppable_switches": command.unstoppable_switches,
            "gasless_controls": command.gasless_controls,
            "unstoppable_threshold": command.unstoppable_threshold,
        }
    )

    mermaid = base_payload.setdefault("mermaid", {})
    mermaid_flow = dedent(
        """
        graph TD
          Owner((Supreme Owner)) --> Identify[Hyper Identify Mesh]
          Identify --> Learn[Open-Ended Curriculum Forge]
          Learn --> Think[Meta-Agentic Tree of Supremacy]
          Think --> Design[Creative Atlas]
          Design --> Strategise[Portfolio Navigator]
          Strategise --> Execute[On-Chain Execution Fabric]
          Execute --> Govern[Guardian Meta-Conductor]
          Govern --> Sustain[Owner Supremacy Matrix]
          Sustain --> Owner
          Owner -->|Override Scripts| Execute
          Owner -->|Parameter Switches| Strategise
          subgraph Supremacy["Supremacy Flywheel"]
            Telemetry((Telemetry))
            Autopilot((Autopilot))
            Treasury((Treasury))
            Guardians((Guardian Mesh))
            CI((CI V2 Grid))
            Gasless((Gasless Fabric))
            Telemetry --> Autopilot
            Autopilot --> Treasury
            Treasury --> Guardians
            Guardians --> CI
            CI --> Gasless
            Gasless --> Execute
          end
          Execute --> Supremacy
          Supremacy --> Execute
        """
    ).strip()

    mermaid_radar = dedent(
        f"""
        %%{{init: {{'theme': 'dark'}} }}%%
        radarChart
          title Supremacy Capability Radar
          axes Automation, Resilience, Empowerment, Velocity, Stewardship, Expansion
          dataset Owner
            data {owner_empowerment:.2f}, {guardian_resilience:.2f}, {supremacy_index:.2f}, {expansion_thrust:.2f}, {meta_ci_health:.2f}, {capital_flywheel_index:.2f}
        """
    ).strip()

    mermaid_sequence = dedent(
        """
        sequenceDiagram
          participant Owner as Supreme Owner
          participant Console as Supremacy Console
          participant Planner as Meta-Agentic Planner
          participant Guardians as Guardian Council
          participant Chain as AGI Jobs v0 (v2)
          participant Treasury as Treasury Autopilot
          Owner->>Console: Launch Supremacy Scenario
          Console->>Planner: Upload V10 scenario YAML
          Planner->>Guardians: Stream unstoppable levers & antifragility checks
          Guardians->>Treasury: Approve hyper-bridge & reserves
          Treasury->>Chain: Simulate 4337 execution + treasury routing
          Chain-->>Console: CI V2 verdicts + receipts + telemetry
          Console-->>Owner: Render supremacy dashboard & override levers
          Owner->>Chain: Optional unstoppable switch execution
        """
    ).strip()

    mermaid_timeline = dedent(
        """
        gantt
          title Meta-Agentic Supremacy Timeline
          dateFormat X
          axisFormat %s
          section Identify
            Hyper-signal fusion       :done,    0, 1
            Antifragility anomaly scan:active,  1, 1
          section Learn
            Curriculum escalation     :        2, 1
            World model distillation  :        3, 2
          section Strategise
            Treasury supremacy mesh   :        5, 1
            Guardian quorum sync      :        6, 1
          section Execute
            4337 dry-run envelope     :        7, 1
            On-chain execution        :        8, 1
            Owner override window     :        9, 1
        """
    ).strip()

    mermaid_journey = dedent(
        """
        journey
          title Owner Empowerment Journey V10
          section Console
            Launch supremacy CLI: 5: owner
            Review unstoppable dashboard: 5: owner
            Trigger override switch: 5: owner
          section Guardians
            Confirm quorum: 5: guardians
            Approve antifragility probes: 5: guardians
            Endorse unstoppable threshold: 5: guardians
          section Treasury
            Stream hyperliquidity: 4: treasury
            Route cross-chain bridges: 4: treasury
        """
    ).strip()

    mermaid_state = dedent(
        """
        stateDiagram-v2
          [*] --> SupremacyReady
          SupremacyReady --> Identify
          Identify --> Learn
          Learn --> Think
          Think --> Design
          Design --> Strategise
          Strategise --> Execute
          Execute --> SupremacyReview
          SupremacyReview --> Execute: Override Script
          SupremacyReview --> [*]
        """
    ).strip()

    mermaid_quadrant = dedent(
        """
        quadrantChart
          title Supremacy Command Quadrant
          x-axis Automation <---> Human Oversight
          y-axis Passive <---> Proactive
          "Owner Override Mesh" : 0.40 : 0.92
          "Guardian Meta-Mesh" : -0.05 : 0.95
          "CI Enforcement" : 0.68 : 0.72
          "Alpha Factories" : 0.84 : 0.45
          "Autopilot Orchestrators" : 0.60 : 0.82
          "Gasless Fabric" : 0.55 : 0.88
        """
    ).strip()

    mermaid.update(
        {
            "flow_v10": mermaid_flow,
            "radar": mermaid_radar,
            "sequence_v10": mermaid_sequence,
            "gantt_v10": mermaid_timeline,
            "journey_v10": mermaid_journey,
            "state_v10": mermaid_state,
            "quadrant_v10": mermaid_quadrant,
        }
    )

    mermaid['flow'] = mermaid_flow
    mermaid['sequence'] = mermaid_sequence
    mermaid['gantt'] = mermaid_timeline
    mermaid['journey'] = mermaid_journey
    mermaid['state'] = mermaid_state
    mermaid['quadrant'] = mermaid_quadrant
    base_payload.update(
        {
            "supremacy": supremacy,
            "mission_threads": mission_threads,
            "autopilot": autopilot,
            "treasury_streams": treasury_streams,
            "unstoppable_matrix": unstoppable_matrix,
            "ci_v2": ci_v2,
            "guardian_mesh": guardian_mesh,
            "opportunity_graph": opportunity_graph,
            "command_matrix": {
                "mission_threads": command.mission_threads,
                "unstoppable_initiatives": command.unstoppable_initiatives,
                "telemetry_channels": command.telemetry_channels,
                "autopilot_modes": command.autopilot_modes,
                "supremacy_vectors": command.supremacy_vectors,
            },
        }
    )
    base_payload.setdefault("metrics", {})
    base_payload["metrics"]["scoreboard"] = scoreboard
    return base_payload


def generate_supremacy_report(package_root: Path, summary: Dict[str, Any], dashboard: Dict[str, Any]) -> Path:
    """Render the V10 Supremacy Masterplan markdown deck."""

    reports_dir = package_root / "reports" / "generated"
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / "alpha_meta_supremacy_masterplan.md"

    timeline_block = dashboard.get("timeline", {})
    if isinstance(timeline_block, Mapping):
        timeline_events = timeline_block.get("events", [])
    else:
        timeline_events = timeline_block
    supremacy = dashboard.get("supremacy", {})
    mission_threads = dashboard.get("mission_threads", {}).get("threads", [])

    report = (
        dedent(
            f"""
            # Meta-Agentic α-AGI Jobs Demo V10 — Supremacy Masterplan

            **Run ID:** {summary.get('runId', 'unknown')}  \\
            **Scenario:** {summary.get('scenarioId', 'meta-agentic-alpha-v10')}  \\
            **Owner Empowerment:** {dashboard['metrics']['owner_empowerment']*100:.2f}%  \\
            **Supremacy Index:** {dashboard['metrics']['supremacy_index']*100:.2f}%  \\
            **Unstoppable Readiness:** {dashboard['metrics']['unstoppable_readiness']*100:.2f}%

            ## Supremacy Capability Radar

            ```mermaid
            {dashboard['mermaid']['radar']}
            ```

            ## Supremacy Flywheel Flow

            ```mermaid
            {dashboard['mermaid']['flow_v10']}
            ```

            ## Guardian Coordination Sequence

            ```mermaid
            {dashboard['mermaid']['sequence_v10']}
            ```

            ## Timeline

            ```mermaid
            {dashboard['mermaid']['gantt_v10']}
            ```

            ## Owner Journey

            ```mermaid
            {dashboard['mermaid']['journey_v10']}
            ```

            ## Supremacy State Machine

            ```mermaid
            {dashboard['mermaid']['state_v10']}
            ```

            ## Command Quadrant

            ```mermaid
            {dashboard['mermaid']['quadrant_v10']}
            ```

            ## Supremacy Matrix

            ```json
            {json.dumps(supremacy, indent=2)}
            ```

            ## Mission Threads

            {os.linesep.join(f"- **{item['id']}** — {item['title']}" for item in mission_threads)}

            ## Execution Timeline

            {os.linesep.join(f"- **{event['time']}** — {event['event']}" for event in timeline_events)}

            ## Scoreboard Snapshot

            ```json
            {json.dumps(dashboard['metrics']['scoreboard'], indent=2)}
            ```
            """
        ).strip()
        + "\n"
    )

    path.write_text(report, encoding="utf-8")
    return path


def run_meta_supremacy_demo(
    config_path: Path | None = None,
    *,
    timeout: float = 240.0,
) -> MetaSupremacyOutcome:
    """Execute the Meta-Agentic α-AGI Jobs V10 demo end-to-end."""

    if config_path is None:
        config_path = DEFAULT_CONFIG_PATH
    config = load_configuration(config_path)
    command_matrix = validate_owner_supremacy(config)

    package_root = config.base_dir
    demo_root = package_root.parent

    env_map = prepare_environment(demo_root)
    outcome = run_demo(config, timeout=timeout)

    summary = json.loads(outcome.summary_path.read_text(encoding="utf-8"))
    summary["approvals"] = config.approvals
    summary["scenarioId"] = config.payload.get("scenario", {}).get("id")
    summary["agents"] = outcome.metadata.get("onboarded_agents", [])

    scoreboard_path = Path(env_map["ORCHESTRATOR_SCOREBOARD_PATH"])
    scoreboard = outcome.scoreboard_snapshot or {}
    if not scoreboard_path.exists():
        scoreboard_path.write_text(json.dumps(scoreboard, ensure_ascii=False, indent=2), encoding="utf-8")

    dashboard_payload = generate_supremacy_dashboard(package_root, summary, scoreboard, command_matrix)
    dashboard_path = package_root / "ui" / "dashboard-data-v10.json"
    dashboard_path.write_text(json.dumps(dashboard_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    report_path = generate_supremacy_report(package_root, summary, dashboard_payload)

    latest_run_path = demo_root / "storage" / "latest_run_v10.json"
    latest_run_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    return MetaSupremacyOutcome(
        base=outcome,
        summary_path=latest_run_path,
        dashboard_path=dashboard_path,
        report_path=report_path,
        scoreboard_path=scoreboard_path,
        dashboard_payload=dashboard_payload,
        command_matrix=command_matrix,
    )


__all__ = [
    "DEFAULT_CONFIG_PATH",
    "OwnerSupremacyMandate",
    "MetaSupremacyOutcome",
    "prepare_environment",
    "validate_owner_supremacy",
    "generate_supremacy_dashboard",
    "generate_supremacy_report",
    "run_meta_supremacy_demo",
]
