replicaCount: 1
image:
  repository: ghcr.io/example/attester
  tag: "0.1.0"
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  type: ClusterIP
  port: 7000
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
env:
  logLevel: info
  kmsKey: ""
  schemaUID: ""
  extra: {}
secretRefs: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
probe:
  enabled: true
  path: /healthz
  port: http
  initialDelaySeconds: 10
  periodSeconds: 30
