global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

rule_files:
  - rules.yaml

scrape_configs:
  - job_name: orchestrator
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        action: keep
        regex: orchestrator
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
  - job_name: bundler
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        action: keep
        regex: bundler
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
  - job_name: paymaster-supervisor
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        action: keep
        regex: paymaster-supervisor
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
  - job_name: attester
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        action: keep
        regex: attester
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
  - job_name: ipfs
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        action: keep
        regex: ipfs
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: api
  - job_name: graph-node
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
        action: keep
        regex: graph-node
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: status
