apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: aa-slo-rules
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
    - name: slo.latency
      rules:
        - record: aa:tto_seconds:avg5m
          expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="orchestrator"}[5m])) by (le))
        - record: aa:cpvo_usd:avg5m
          expr: avg_over_time(paymaster_sponsored_cost_usd[5m])
        - record: aa:success_rate:ratio5m
          expr: sum(rate(orchestrator_requests_total{status!~"5.."}[5m])) / sum(rate(orchestrator_requests_total[5m]))
        - record: aa:sponsored_ops_total:sum5m
          expr: sum(rate(paymaster_sponsored_operations_total[5m]))
        - record: aa:sponsored_ops_rejections:sum5m
          expr: sum(rate(paymaster_rejections_total[5m]))
        - record: aa:ipfs_pin_latency_seconds:p95
          expr: histogram_quantile(0.95, sum(rate(ipfs_pin_latency_seconds_bucket[5m])) by (le))
        - record: aa:subgraph_lag_seconds:max
          expr: max(graph_node_subgraph_lag_seconds)
    - name: alerts
      rules:
        - alert: GasTreasuryLow
          expr: min(paymaster_treasury_balance_usd) < 200
          for: 10m
          annotations:
            summary: "Paymaster treasury under $200"
            description: "Top-up the paymaster treasury to avoid rejected sponsorships."
            runbook_url: https://docs.example.com/runbooks/paymaster-top-up
        - alert: SponsorshipRejectSpike
          expr: increase(paymaster_rejections_total[5m]) > 10
          for: 10m
          annotations:
            summary: "Paymaster rejection spike"
            description: "Investigate RPC health, gas price, and schema validity."
            runbook_url: https://docs.example.com/runbooks/rejections
        - alert: SponsoredRevertSpike
          expr: increase(orchestrator_reverted_operations_total[5m]) > 5
          for: 5m
          annotations:
            summary: "Sponsored operations reverting"
            description: "Review upstream contracts and mempool health."
            runbook_url: https://docs.example.com/runbooks/revert-spike
