// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

// Shared AGI Jobs v2 constants.
// @dev Auto-generated by scripts/generate-constants.ts
// Canonical $AGIALPHA token on Ethereum mainnet.
address constant AGIALPHA = 0xA61a3B3a130a9c20768EEBF97E21515A6046a1fA;

// Canonical burn address.
address constant BURN_ADDRESS = 0x000000000000000000000000000000000000dEaD;

// Standard decimals for $AGIALPHA.
uint8 constant AGIALPHA_DECIMALS = 18;

// Scaling factor for token amounts.
uint256 constant TOKEN_SCALE = 10 ** AGIALPHA_DECIMALS;
