replicaCount: 1
image:
  repository: ghcr.io/example/paymaster-supervisor
  tag: "0.1.0"
  digest: ""
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  type: ClusterIP
  port: 4000
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
env:
  logLevel: info
  allowlist: []
  extra: {}
  kms:
    keyUri: ""
    endpoint: ""
    region: ""
    digest: sha256
    localDebugSecret: ""
secretRefs: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
probe:
  enabled: true
  path: /healthz
  port: http
  initialDelaySeconds: 10
  periodSeconds: 30
