image:
  repository: ghcr.io/example/paymaster-supervisor
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
resources: {}
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuTargetPercentage: 75
env: {}
secrets: {}
