apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "postgres.labels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-headless
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "postgres.labels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
