image:
  repository: ghcr.io/graphprotocol/graph-node
  tag: v0.32.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
resources: {}
config:
  ethereumNetworks:
    - name: sepolia
      rpc: https://ethereum-sepolia.publicnode.com
  postgres:
    host: ""
    database: subgraph
    userSecret: graph-node-postgres
  ipfs:
    endpoint: ""
monitoring:
  enabled: true
