apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    app.kubernetes.io/name: ipfs
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: swarm
      port: {{ .Values.service.swarmPort }}
      targetPort: swarm
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
  selector:
    app.kubernetes.io/name: ipfs
    app.kubernetes.io/instance: {{ .Release.Name }}
