apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ipfs.labels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: swarm
      port: {{ .Values.service.swarmPort }}
      targetPort: swarm
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}-headless
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "ipfs.labels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
