{{- $global := default (dict) .Values.global -}}
{{- $observability := default (dict) $global.observability -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ipfs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ipfs
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "ipfs.fullname" . }}
  template:
    metadata:
      annotations:
        {{- if (default false $observability.prometheusScrape) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.apiPort }}"
        {{- end }}
        {{- range $k, $v := .Values.podAnnotations }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ipfs
          image: {{ include "ipfs.imageWithDigest" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.apiPort }}
              name: api
            - containerPort: {{ .Values.service.gatewayPort }}
              name: gateway
          env:
            - name: IPFS_PROFILE
              value: server
            - name: LIBP2P_FORCE_PNET
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /data/ipfs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
