global:
  scrape_interval: 15s

scrape_configs:
  - job_name: arena-orchestrator
    static_configs:
      - targets: ["arena-orchestrator:9464"]
  - job_name: culture-indexer
    static_configs:
      - targets: ["culture-indexer:9464"]
