import * as fs from 'fs';
import * as path from 'path';

const configPath = path.join(__dirname, '..', 'config', 'agialpha.json');
const { address, decimals } = JSON.parse(fs.readFileSync(configPath, 'utf8')) as { address: string; decimals: number };

const content = `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.25;\n\n// Shared AGI Jobs v2 constants.\n// @dev Auto-generated by scripts/generate-constants.ts\n// Canonical $AGIALPHA token on Ethereum mainnet.\naddress constant AGIALPHA = ${address};\n\n// Standard decimals for $AGIALPHA.\nuint8 constant AGIALPHA_DECIMALS = ${decimals};\n`;

const outPath = path.join(__dirname, '..', 'contracts', 'v2', 'Constants.sol');
fs.writeFileSync(outPath, content);
console.log(`Generated ${outPath}`);
