global: {}
replicaCount: 1
image:
  repository: bundler
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8090
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: null
resources: {}
podAnnotations: {}
extraEnvFrom: []
