image:
  repository: ghcr.io/agi/jobs/bundler
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
resources: {}
config:
  rpcUrl: https://ethereum-sepolia.publicnode.com
  entryPoint: "0x0000000000000000000000000000000000000000"
  bundleIntervalSeconds: 5
monitoring:
  enabled: true
