apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymasterSupervisor.fullname" . }}
  labels:
    app.kubernetes.io/name: paymaster-supervisor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: paymaster
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: paymaster-supervisor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: paymaster-supervisor
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: paymaster-supervisor
          {{- $repoPrefix := default "" (dig "image" "repositoryPrefix" .Values.global) }}
          {{- $repository := default (printf "%s/paymaster-supervisor" $repoPrefix | trimPrefix "/") .Values.image.repository }}
          {{- $digest := coalesce .Values.image.digest (dig "image" "digestOverrides" "paymaster-supervisor" .Values.global) }}
          {{- $tag := coalesce .Values.image.tag (dig "image" "tag" .Values.global) }}
          image: {{ $repository }}{{- if $digest -}}@{{ $digest }}{{- else -}}:{{ required "image.tag must be provided when no digest is configured for paymaster-supervisor" $tag }}{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RPC_URL
              value: {{ default (dig "rpc" "primary" .Values.global) .Values.config.rpcUrl | required "config.rpcUrl or global.rpc.primary must be set" | quote }}
            - name: PAYMASTER_ADDRESS
              value: {{ default (dig "contracts" "paymaster" .Values.global) .Values.config.paymasterAddress | required "config.paymasterAddress or global.contracts.paymaster must be set" | quote }}
            - name: TREASURY_ADDRESS
              value: {{ default (dig "secrets" "paymaster" "treasuryAddress" .Values.global) .Values.config.treasuryAddress | required "config.treasuryAddress or global.secrets.paymaster.treasuryAddress must be set" | quote }}
            - name: SPONSORSHIP_BUDGET_USD
              value: {{ default 100.0 .Values.config.sponsorshipBudgetUsd | quote }}
            - name: KMS_KEY_URI
              value: {{ default (dig "secrets" "paymaster" "kmsKeyUri" .Values.global) .Values.config.kmsKey | required "config.kmsKey or global.secrets.paymaster.kmsKeyUri must be set" | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
