apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paymasterSupervisor.fullname" . }}
  labels:
    app.kubernetes.io/name: paymaster-supervisor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: paymaster
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: paymaster-supervisor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: paymaster-supervisor
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: paymaster-supervisor
          image: {{ .Values.image.repository }}{{- if .Values.image.digest -}}@{{ .Values.image.digest }}{{- else -}}:{{ .Values.image.tag }}{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RPC_URL
              value: {{ default (dig "rpc" "primary" .Values.global) .Values.config.rpcUrl | required "config.rpcUrl or global.rpc.primary must be set" | quote }}
            - name: PAYMASTER_ADDRESS
              value: {{ default (dig "contracts" "paymaster" .Values.global) .Values.config.paymasterAddress | required "config.paymasterAddress or global.contracts.paymaster must be set" | quote }}
            - name: TREASURY_ADDRESS
              value: {{ required "config.treasuryAddress is required" .Values.config.treasuryAddress | quote }}
            - name: SPONSORSHIP_BUDGET_USD
              value: {{ default 100.0 .Values.config.sponsorshipBudgetUsd | quote }}
            - name: KMS_KEY_URI
              value: {{ default (dig "secrets" "paymaster" "kmsKey" .Values.global) .Values.config.kmsKey | required "config.kmsKey or global.secrets.paymaster.kmsKey must be set" | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
