apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bundler.fullname" . }}-config
  labels:
    app.kubernetes.io/name: bundler
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.json: |
    {
      "bundleIntervalSeconds": {{ default 5 .Values.config.bundleIntervalSeconds }}
    }
