{{- $global := default (dict) .Values.global -}}
{{- $contracts := default (dict) $global.contracts -}}
{{- $rpc := default (dict) $global.rpc -}}
{{- $observability := default (dict) $global.observability -}}
{{- $ratelimits := default (dict) $global.ratelimits -}}
{{- $secrets := default (dict) $global.secrets -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bundler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: bundler
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if (default false $observability.prometheusScrape) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        {{- end }}
        {{- range $k, $v := .Values.podAnnotations }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: bundler
          image: {{ include "bundler.imageWithDigest" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: ENTRYPOINT_ADDRESS
              value: {{ default "" $contracts.entryPoint | quote }}
            - name: PAYMASTER_ADDRESS
              value: {{ default "" $contracts.paymaster | quote }}
            - name: BUNDLER_PRIVATE_RPC
              value: {{ default "" $rpc.primary | quote }}
            - name: RATE_LIMIT_ENABLED
              value: {{ default false $ratelimits.enabled | quote }}
            - name: RATE_LIMIT_BURST
              value: {{ default 20 $ratelimits.burst | quote }}
            - name: RATE_LIMIT_RPS
              value: {{ default 10 $ratelimits.requestsPerSecond | quote }}
          envFrom:
            - secretRef:
                name: {{ default (printf "%s-runtime" (include "bundler.fullname" .)) $secrets.runtimeSecretName }}
            {{- range .Values.extraEnvFrom }}
            - {{ toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
