image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5432
resources: {}
persistence:
  size: 20Gi
config:
  database: subgraph
  username: graph
  existingSecret: graph-node-postgres
monitoring:
  enabled: true
