apiVersion: v1
kind: Secret
metadata:
  name: graph-node-postgres
  labels:
    app.kubernetes.io/name: graph-node
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: change-me
