apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: graph-node
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: query
      name: query
    - port: {{ .Values.indexer.adminPort }}
      targetPort: admin
      name: admin
    - port: {{ .Values.indexer.metricsPort }}
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
