apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-node.fullname" . }}
  labels:
    {{- include "graph-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "graph-node.selectorLabels" . | nindent 4 }}
  ports:
    - name: query
      port: {{ .Values.service.queryPort }}
      targetPort: query
    - name: status
      port: {{ .Values.service.statusPort }}
      targetPort: status
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
