// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

/// @dev Shared AGI Jobs v2 constants (auto-generated by scripts/generate-constants.ts).
/// @dev Canonical $AGIALPHA token on Ethereum mainnet.
address constant AGIALPHA = 0xA61a3B3a130a9c20768EEBF97E21515A6046a1fA;
/// @dev Standard decimals for $AGIALPHA.
uint8 constant AGIALPHA_DECIMALS = 18;
/// @dev Base unit scaling factor for $AGIALPHA (10 ** decimals).
uint256 constant TOKEN_SCALE = 1_000_000_000_000_000_000;
/// @dev Address used for burning tokens.
address constant BURN_ADDRESS = 0x0000000000000000000000000000000000000000;
