name: contracts-ci

on:
  pull_request:
    paths:
      - 'contracts/**'
      - 'scripts/**'
      - 'test/**'
      - 'hardhat.config.*'
      - 'package*.json'
      - '.github/workflows/contracts.yml'
  push:
    branches: [main]
    paths:
      - 'contracts/**'
      - 'scripts/**'
      - 'test/**'
      - 'hardhat.config.*'
      - 'package*.json'
      - '.github/workflows/contracts.yml'

permissions:
  contents: read

concurrency:
  group: contracts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-test:
    runs-on: ubuntu-24.04

    env:
      COVERAGE_MIN: '90'
      ACCESS_CONTROL_PATHS: 'contracts/v2/admin,contracts/v2/governance'

      FEE_PCT: '0.02'
      BURN_PCT: '0.06'
      TREASURY: '0x1111111111111111111111111111111111111111'
      VALIDATORS_PER_JOB: '3'
      REQUIRED_APPROVALS: '3'
      COMMIT_WINDOW: '30m'
      REVEAL_WINDOW: '30m'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            auth.docker.io:443
            binaries.soliditylang.org:443
            codeload.github.com:443
            download.docker.com:443
            foundry.paradigm.xyz:443
            ghcr.io:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
            production.cloudflare.docker.com:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443
            storage.googleapis.com:443
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Compile
        env:
          COVERAGE_MIN: 90
        run: |
          npx ts-node --compiler-options '{"module":"commonjs"}' scripts/generate-constants.ts
          npx hardhat compile

      - name: Regenerate constants for tests
        run: npx ts-node --compiler-options '{"module":"commonjs"}' scripts/generate-constants.ts

      - name: Node/Hardhat tests
        run: npm test

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@50d5a8956f2e319df19e6b57539d7e2acb9f8c1e
        with:
          version: 'v1.4.0'

      - name: Foundry tests
        run: forge test -vvvv --ffi --fuzz-runs 256 --match-contract 'CommitReveal|Stake|Fee|Slashing'
