name: contracts-ci

on:
  pull_request:
    paths:
      - 'contracts/**'
      - 'scripts/**'
      - 'test/**'
      - 'hardhat.config.*'
      - 'package*.json'
      - '.github/workflows/contracts.yml'
  push:
    branches: [main]
    paths:
      - 'contracts/**'
      - 'scripts/**'
      - 'test/**'
      - 'hardhat.config.*'
      - 'package*.json'
      - '.github/workflows/contracts.yml'

permissions:
  contents: read

concurrency:
  group: contracts-${{ github.ref }}
  cancel-in-progress: true

env:
  ACCESS_CONTROL_PATHS: 'contracts/v2/admin,contracts/v2/governance'
  FEE_PCT: '0.02'
  BURN_PCT: '0.06'
  TREASURY: '0x1111111111111111111111111111111111111111'
  VALIDATORS_PER_JOB: '3'
  REQUIRED_APPROVALS: '3'
  COMMIT_WINDOW: '30m'
  REVEAL_WINDOW: '30m'
  COVERAGE_MIN: '90'

jobs:
  compile-and-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Hardhat compiler builds
        uses: actions/cache@v4
        with:
          path: ~/.cache/hardhat-nodejs
          key: ${{ runner.os }}-hardhat-solc-${{ hashFiles('hardhat.config.*', 'package-lock.json', 'scripts/generate-constants.ts') }}
          restore-keys: |
            ${{ runner.os }}-hardhat-solc-

      - name: Install dependencies
        run: npm ci

      - name: Compile
        env:
          COVERAGE_MIN: 90
        run: |
          npx ts-node --compiler-options '{"module":"commonjs"}' scripts/generate-constants.ts
          npx hardhat compile

      - name: Regenerate constants for tests
        run: npx ts-node --compiler-options '{"module":"commonjs"}' scripts/generate-constants.ts

      - name: Node/Hardhat tests
        run: npm test

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Foundry tests
        run: forge test -vvvv --ffi --fuzz-runs 256 --match-contract 'CommitReveal|Stake|Fee|Slashing'
