name: demo-alpha-agi-mark

on:
  pull_request:
    paths:
      - 'demo/alpha-agi-mark/**'
      - 'contracts/demo/alpha-agi-mark/**'
      - 'test/alphaAgiMark.test.ts'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/demo-alpha-agi-mark.yml'
  push:
    branches: [main]
    paths:
      - 'demo/alpha-agi-mark/**'
      - 'contracts/demo/alpha-agi-mark/**'
      - 'test/alphaAgiMark.test.ts'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/demo-alpha-agi-mark.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  alpha-agi-mark-demo:
    name: α-AGI MARK foresight exchange
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Harden runner
        uses: step-security/harden-runner@v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: |
            api.github.com
            github.com
            objects.githubusercontent.com
            raw.githubusercontent.com
            registry.npmjs.org
            nodejs.org

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run α-AGI MARK tests
        run: npm run test:alpha-agi-mark

      - name: Run α-AGI MARK demo
        run: npm run demo:alpha-agi-mark

      - name: Upload α-AGI MARK artefacts
        uses: actions/upload-artifact@v4
        with:
          name: alpha-agi-mark-artifacts
          path: reports/alpha-agi-mark/**
          if-no-files-found: ignore
