name: demo-meta-agentic-program-synthesis

on:
  pull_request:
    paths:
      - 'demo/Meta-Agentic-Program-Synthesis-v0/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/demo-meta-agentic-program-synthesis.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  meta-agentic-demo:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          egress-policy: block
          allowed-endpoints: |
            api.github.com
            github.com
            objects.githubusercontent.com
            raw.githubusercontent.com
            registry.npmjs.org
            nodejs.org

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --progress=false

      - name: Run deterministic mission tests
        run: npm run demo:meta-agentic-program-synthesis:test

      - name: Generate full sovereign dossier
        run: npm run demo:meta-agentic-program-synthesis:full

      - name: Upload synthesis artefacts
        uses: actions/upload-artifact@v4
        with:
          name: meta-agentic-program-synthesis-reports
          path: demo/Meta-Agentic-Program-Synthesis-v0/reports
