name: demo-celestial-sovereign

on:
  pull_request:
    paths:
      - 'demo/CELESTIAL-SOVEREIGN-ORBITAL-AGI-OS-GRAND-DEMONSTRATION/**'
      - 'scripts/v2/celestialSovereignDemo.ts'
      - '.github/workflows/demo-celestial-sovereign.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  celestial-sovereign:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Harden runner
        uses: step-security/harden-runner@v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: |
            api.github.com
            github.com
            objects.githubusercontent.com
            raw.githubusercontent.com
            registry.npmjs.org
            nodejs.org

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: '1.4.0'

      - name: Run Celestial Sovereign demo
        run: npm run demo:celestial-sovereign -- --auto-yes --launch-compose=false --skip-owner-plan=false --skip-owner-surface=false --skip-branch-protection=false

      - name: Upload celestial artefacts
        uses: actions/upload-artifact@v4
        with:
          name: celestial-sovereign-artefacts
          path: |
            reports/agi-os/**
            reports/celestial-sovereign/**
