name: demo-alpha-agi-mark

on:
  pull_request:
    paths:
      - 'demo/alpha-agi-mark/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/demo-alpha-agi-mark.yml'
  push:
    branches: [main]
    paths:
      - 'demo/alpha-agi-mark/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/demo-alpha-agi-mark.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  alpha-agi-mark-demo:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          egress-policy: block
          allowed-endpoints: |
            api.github.com
            github.com
            objects.githubusercontent.com
            raw.githubusercontent.com
            registry.npmjs.org
            nodejs.org

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --progress=false

      - name: Run α-AGI MARK unit tests
        run: npm run test:alpha-agi-mark

      - name: Execute α-AGI MARK foresight demo
        run: npm run demo:alpha-agi-mark:ci

      - name: Validate recap dossier
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = 'demo/alpha-agi-mark/reports/alpha-mark-recap.json';
          if (!fs.existsSync(path)) {
            throw new Error('recap file missing');
          }
          const data = JSON.parse(fs.readFileSync(path, 'utf8'));
          const requiredContracts = ['novaSeed', 'riskOracle', 'markExchange'];
          if (!data.contracts) throw new Error('contracts block missing');
          for (const key of requiredContracts) {
            if (!data.contracts[key]) {
              throw new Error(`contract address missing for ${key}`);
            }
          }
          if (!data.contracts.sovereignVault) {
            throw new Error('contract address missing for sovereignVault');
          }
          if (!data.validators || data.validators.approvalCount === undefined) {
            throw new Error('validator consensus details missing');
          }
          if (!data.ownerControls || data.ownerControls.treasury === undefined) {
            throw new Error('owner controls snapshot missing');
          }
          if (!Array.isArray(data.participants) || data.participants.length === 0) {
            throw new Error('participants missing');
          }
          if (!Array.isArray(data.timeline) || data.timeline.length === 0) {
            throw new Error('timeline missing');
          }
          if (!data.launch || !data.launch.finalized) {
            throw new Error('launch did not finalize');
          }
          if (!data.launch.sovereignVault || !data.launch.sovereignVault.decodedMetadata) {
            throw new Error('sovereign vault details missing');
          }
          console.log(`Validated α-AGI MARK recap for ${data.participants.length} participants.`);
          NODE

      - name: Validate sovereign dashboard
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = 'demo/alpha-agi-mark/reports/alpha-mark-dashboard.html';
          if (!fs.existsSync(path)) {
            throw new Error('dashboard file missing');
          }
          const html = fs.readFileSync(path, 'utf8');
          const requiredSnippets = [
            'MARK Launch Telemetry',
            'Mission Control Metrics',
            'Mission Timeline',
            'class="mermaid"',
            'Owner Control Deck',
          ];
          for (const snippet of requiredSnippets) {
            if (!html.includes(snippet)) {
              throw new Error(`dashboard missing snippet: ${snippet}`);
            }
          }
          console.log('Dashboard dossier structure validated.');
          NODE

      - name: Offline recap triangulation
        run: npm run verify:alpha-agi-mark

      - name: Build integrity dossier
        run: npm run integrity:alpha-agi-mark

      - name: Validate integrity dossier
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = 'demo/alpha-agi-mark/reports/alpha-mark-integrity.md';
          if (!fs.existsSync(path)) {
            throw new Error('integrity dossier missing');
          }
          const content = fs.readFileSync(path, 'utf8');
          const requiredSections = [
            '# α-AGI MARK Integrity Report',
            '## Confidence Summary',
            '```mermaid',
            'Owner Command Deck Snapshot',
          ];
          for (const section of requiredSections) {
            if (!content.includes(section)) {
              throw new Error(`integrity dossier missing section: ${section}`);
            }
          }
          console.log('Integrity dossier validated.');
          NODE

      - name: Forge empowerment pulse dossier
        run: npm run pulse:alpha-agi-mark

      - name: Validate empowerment pulse dossier
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = 'demo/alpha-agi-mark/reports/alpha-mark-empowerment.md';
          if (!fs.existsSync(path)) {
            throw new Error('empowerment dossier missing');
          }
          const content = fs.readFileSync(path, 'utf8');
          const requiredSections = [
            '# α-AGI MARK Empowerment Pulse',
            '## Mission Snapshot',
            '```mermaid',
            '## Operator Command Deck',
          ];
          for (const section of requiredSections) {
            if (!content.includes(section)) {
              throw new Error(`empowerment dossier missing section: ${section}`);
            }
          }
          console.log('Empowerment pulse dossier validated.');
          NODE

      - name: Render mission timeline
        run: npm run timeline:alpha-agi-mark

      - name: Validate mission timeline
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = 'demo/alpha-agi-mark/reports/alpha-mark-timeline.md';
          if (!fs.existsSync(path)) {
            throw new Error('mission timeline dossier missing');
          }
          const content = fs.readFileSync(path, 'utf8');
          const required = ['# α-AGI MARK Mission Timeline', '```mermaid', '| # | Phase | Event | Details | Actor |'];
          for (const needle of required) {
            if (!content.includes(needle)) {
              throw new Error(`timeline dossier missing section: ${needle}`);
            }
          }
          console.log('Mission timeline dossier validated.');
          NODE

      - name: Upload α-AGI MARK recap
        uses: actions/upload-artifact@v4
        with:
          name: alpha-agi-mark-recap
          path: demo/alpha-agi-mark/reports/alpha-mark-recap.json

      - name: Upload α-AGI MARK integrity dossier
        uses: actions/upload-artifact@v4
        with:
          name: alpha-agi-mark-integrity
          path: demo/alpha-agi-mark/reports/alpha-mark-integrity.md

      - name: Upload α-AGI MARK empowerment pulse
        uses: actions/upload-artifact@v4
        with:
          name: alpha-agi-mark-empowerment
          path: demo/alpha-agi-mark/reports/alpha-mark-empowerment.md

      - name: Upload α-AGI MARK mission timeline
        uses: actions/upload-artifact@v4
        with:
          name: alpha-agi-mark-timeline
          path: demo/alpha-agi-mark/reports/alpha-mark-timeline.md
