name: Nightly Security

env:
  NODE_VERSION: '20.12.2'

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  echidna-long:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Authenticate to GitHub Container Registry
        env:
          GHCR_USER: ${{ github.actor }}
          GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$GHCR_PAT" ]; then
            echo "::error::GITHUB_TOKEN unavailable; cannot authenticate to ghcr.io" && exit 1
          fi
          echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
      - name: Echidna long fuzz (Docker)
        run: |
          docker run --rm -v "$PWD":/src -w /src ghcr.io/crytic/echidna:2.2.7 \
            echidna-test ./contracts/test/CommitRevealEchidna.sol \
              --contract CommitRevealEchidnaHarness \
              --config ./echidna/echidna.long.yml \
              --test-mode assertion \
              --corpus-dir echidna/corpus \
              --seed 42 \
              --max-steps 500000
