name: Nightly Security

env:
  NODE_VERSION: '20.12.2'
  ECHIDNA_IMAGE: 'ghcr.io/crytic/echidna/echidna:v2.2.7'

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  echidna-long:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install deps (npm ci, exact lockfile)
        run: npm ci
      - name: Prepare writable Foundry artifacts directories
        run: |
          chmod a+rwX .
          mkdir -p out cache
          chmod -R a+rwX out cache
      - name: Authenticate to GitHub Container Registry
        env:
          GHCR_USER: ${{ github.actor }}
          GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$GHCR_PAT" ]; then
            echo "::error::GITHUB_TOKEN unavailable; cannot authenticate to ghcr.io" && exit 1
          fi
          echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
      - name: Echidna long fuzz (Docker)
        run: |
          docker run --rm -v "$PWD":/src -w /src "$ECHIDNA_IMAGE" \
            echidna-test ./contracts/test/CommitRevealEchidna.sol \
              --contract CommitRevealEchidnaHarness \
              --config ./echidna/echidna.long.yml \
              --test-mode assertion \
              --corpus-dir echidna/corpus \
              --seed 42 \
              --max-steps 500000
