name: Nightly Security

env:
  NODE_VERSION: '20.12.2'

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  echidna-long:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Echidna long fuzz (Docker)
        run: |
          docker run --rm -v "$PWD":/src -w /src ghcr.io/crytic/echidna:2.2.7 \
            echidna-test ./contracts/test/CommitRevealEchidna.sol \
              --contract CommitRevealEchidnaHarness \
              --config ./echidna/echidna.long.yml \
              --test-mode assertion \
              --corpus-dir echidna/corpus \
              --seed 42 \
              --max-steps 500000
