name: security-scorecard

on:
  schedule:
    - cron: '30 1 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: false

jobs:
  analyze:
    name: OpenSSF Scorecard
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
            codeload.github.com:443
            ghcr.io:443
            registry-1.docker.io:443
            auth.docker.io:443
            index.docker.io:443
            nodejs.org:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443
            storage.googleapis.com:443
            dl.google.com:443
            pypi.org:443
            files.pythonhosted.org:443
            binaries.soliditylang.org:443
            solc-bin.ethereum.org:443
            api.securityscorecards.dev:443
            fulcio.sigstore.dev:443
            rekor.sigstore.dev:443
            oauth2.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN || github.token }}

      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@755f44910c12a3d7ca0d8c6e42c048b3362f7cec
        with:
          sarif_file: scorecard.sarif

      - name: Upload Scorecard artefacts
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ossf-scorecard-report
          path: scorecard.sarif
          if-no-files-found: warn
