name: security

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: read
  security-events: write
  id-token: write

concurrency:
  group: security-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --verbose

      - name: npm audit (fail on high)
        run: npm audit --audit-level=high

      - name: License checker
        run: |
          mkdir -p reports
          npx license-checker --summary --production --development --out reports/license-summary.txt

      - name: Slither static analysis
        run: |
          docker run --rm \
            -v "$PWD":/src \
            -w /src \
            trailofbits/eth-security-toolbox:nightly-20240902 \
            slither . --fail-high --exclude-dependencies --sarif slither.sarif

      - name: Upload Slither SARIF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: slither-sarif
          path: slither.sarif

      - name: Mythril quick scan
        run: |
          docker run --rm \
            -v "$PWD":/src \
            -w /src \
            mythril/myth:0.24.3 \
            analyze contracts/v2/modules/JobRegistryModule.sol \
              --execution-timeout 120 \
              --solc-args "--base-path . --include-path node_modules --allow-paths .,node_modules" \
              --solc-remaps "@openzeppelin=node_modules/@openzeppelin"

      - name: Generate SBOM (SPDX JSON)
        uses: anchore/sbom-action@v0.17.5
        with:
          path: .
          format: spdx-json
          output-file: reports/sbom/spdx.json

      - name: Upload security artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-artifacts
          path: |
            reports/license-summary.txt
            reports/sbom/spdx.json

      - name: Prepare provenance subjects
        if: startsWith(github.ref, 'refs/tags/')
        id: provenance-subjects
        run: |
          set -euo pipefail
          sha_value=$(sha256sum reports/sbom/spdx.json | awk '{print $1}')
          subject_line="${sha_value}  reports/sbom/spdx.json"
          if command -v base64 >/dev/null 2>&1; then
            if [ "$(uname)" = "Darwin" ]; then
              encoded=$(printf "%s" "$subject_line" | base64)
            else
              encoded=$(printf "%s" "$subject_line" | base64 -w0)
            fi
          else
            echo "base64 utility not found" >&2
            exit 1
          fi
          echo "value=$encoded" >> "$GITHUB_OUTPUT"

      - name: Generate provenance attestation
        if: startsWith(github.ref, 'refs/tags/')
        id: generate-provenance
        # v2.0.0 currently references a non-existent actions/delegator-generic path on
        # GitHub-hosted Ubuntu 24.04 runners, so we stay on the latest v1 release until
        # the upstream issue is resolved.
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.10.0
        with:
          base64-subjects: ${{ steps.provenance-subjects.outputs.value }}
          provenance-name: provenance.intoto.jsonl

      - name: Download provenance attestation
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.generate-provenance.outputs.provenance-name }}
          path: reports

      - name: Upload provenance statement
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: reports/provenance.intoto.jsonl
